CREATE TABLE Razza (
	Nome VARCHAR(25) PRIMARY KEY,
	Tipo ENUM ('Cane', 'Gatto') NOT NULL
);

CREATE TABLE Utente (
	Nome VARCHAR(15) PRIMARY KEY,
	Password VARCHAR(255) NOT NULL
);

CREATE TABLE EntitaDatabile (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Note TEXT,
	DataRichiesta DATE NOT NULL DEFAULT (CURRENT_DATE()),
);

CREATE TABLE Calendario (
	ID INT,
	Data DATE,
	Ora TIME,
	PRIMARY KEY(ID, Data, Ora),
	FOREIGN KEY (ID) REFERENCES EntitaDatabile(ID)
);

CREATE TABLE Persona (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Cognome VARCHAR(25) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Telefono CHAR(10) NOT NULL UNIQUE
);

CREATE TABLE AnimaleRifugio (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Storia TEXT NOT NULL,
	Sesso ENUM ('M', 'F') NOT NULL,
	Peso VARCHAR(25) NOT NULL,
	Eta VARCHAR(25) NOT NULL,
	PthImg TEXT NOT NULL UNIQUE,
	Colore VARCHAR(10) NOT NULL,
	Caratteristiche JSON NOT NULL,
	Razza VARCHAR(25) NOT NULL,
	FOREIGN KEY (Razza) REFERENCES Razza(Nome)
);

CREATE TABLE AnimaleEsterno (
	ID INT PRIMARY KEY,
	Sesso ENUM ('M', 'F') NOT NULL,
	Peso VARCHAR(25) NOT NULL,
	Eta VARCHAR(25) NOT NULL,
	Proprietario INT NOT NULL,
	Razza VARCHAR(25) NOT NULL,
	FOREIGN KEY (ID) REFERENCES EntitaDatabile(ID) ON DELETE CASCADE,
	FOREIGN KEY (Proprietario) REFERENCES Persona(ID),
	FOREIGN KEY (Razza) REFERENCES Razza(Nome)
);

CREATE TABLE Ticket (
	ID INT PRIMARY KEY,
	Richiedente INT NOT NULL,
	Animale INT NOT NULL,
	FOREIGN KEY (ID) REFERENCES EntitaDatabile(ID) ON DELETE CASCADE,
	FOREIGN KEY (Richiedente) REFERENCES Persona(ID),
	FOREIGN KEY (Animale) REFERENCES AnimaleRifugio(ID)
);